name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or whatever branch you want to trigger the action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm install gh-pages --save-dev

    - name: Build and Deploy
      env:
        CI: true
      run: |
        npm run deploy -- -m "Deploy Homepage from Action to GitHub Pages"
